DigiMovie/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DigiMovie.Models;
using System.Net;
using DigiMovie.ViewModels;

namespace DigiMovie.Controllers
{
    public class CustomersController : Controller
    {
        #region BaseOperations
        private ApplicationDbContext db;
        public CustomersController()
        {
            db = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }
        #endregion
        public ActionResult Index()
        {
            return View(db.Customers);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var customer = db.Customers.Include("MembershipType").SingleOrDefault(c=>c.Id==id);
            if (customer == null)
                return HttpNotFound();
            return View(customer);
        }

        public ActionResult Create()
        {
            var customersFormViewModel = new CustomersFormViewModel {
                MembershipTypes=db.MembershipTypes
            };
            return View(customersFormViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
            try
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                TempData["State"]= 1;
                return RedirectToAction("Index");
            }
            catch 
            {
                TempData["State"] = 0;
                return RedirectToAction("Create");
            }
            }
            var customersFormViewModel = new CustomersFormViewModel
            {
                Customer = customer,
                MembershipTypes = db.MembershipTypes
            };
            return View(customersFormViewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var customer = db.Customers.Find(id);
            if (customer == null)
                return HttpNotFound();
            var customersFormViewModel = new CustomersFormViewModel
            {
                Customer = customer,
                MembershipTypes = db.MembershipTypes
            };
            return View(customersFormViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer customer)
        {
            //Metod 1
            //var customerInDb = db.Customers.Find(customer.Id);
            //customerInDb.Name = customer.Name;
            //customerInDb.BirthDate = customer.BirthDate;
            //customerInDb.IsSubscribedToNewsLetter = customer.IsSubscribedToNewsLetter;
            //customerInDb.MembershipTypeId = customer.MembershipTypeId;
            if (ModelState.IsValid)
            {
             //Metod 2
            db.Entry(customer).State = System.Data.Entity.EntityState.Modified;
            try
            {
                db.SaveChanges();
                TempData["State"] = 3;
                return RedirectToAction("Index");
            }
            catch 
            {
                TempData["State"] = 2;
                return RedirectToAction("Edit");
            }
            }
            var customersFormViewModel = new CustomersFormViewModel
            {
                Customer = customer,
                MembershipTypes = db.MembershipTypes
            };
            return View(customersFormViewModel);

        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var customer = db.Customers.Find(id);
            if (customer == null)
                return HttpNotFound();
            
            return View(customer);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            try
            {
                db.SaveChanges();
                TempData["State"] = 5;
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["State"] = 4;
                return RedirectToAction("Delete");
            }
           
        }
    }
}

DigiMovie/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DigiMovie.Models;
using System.Net;
using DigiMovie.ViewModels;

namespace DigiMovie.Controllers
{
    public class MoviesController : Controller
    {
        #region BaseOperations
        private ApplicationDbContext db;
        public MoviesController()
        {
            db = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }
        #endregion
        public ActionResult Index()
        {
            return View(db.Movies);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var movie = db.Movies.Include("Genre").SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return HttpNotFound();
            return View(movie);
        }

        public ActionResult Create()
        {
            var moviesFormViewModel = new MoviesFormViewModel
            {
                Genres = db.Genres
            };
            return View(moviesFormViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Movie movie)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    movie.DateAdded = DateTime.Now;
                    db.Movies.Add(movie);
                    db.SaveChanges();
                    TempData["State"] = 1;
                    return RedirectToAction("Index");
                }
                catch
                {
                    TempData["State"] = 0;
                    return RedirectToAction("Create");
                }
            }
            var moviesFormViewModel = new MoviesFormViewModel
            {
                Movie = movie,
                Genres = db.Genres
            };
            return View(moviesFormViewModel);

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var movie = db.Movies.Find(id);
            if (movie == null)
                return HttpNotFound();
            var moviesFormViewModel = new MoviesFormViewModel
            {
                Movie = movie,
                Genres = db.Genres
            };
            return View(moviesFormViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Movie movie)
        {    
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(movie).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    TempData["State"] = 3;
                    return RedirectToAction("Index");
                }
                catch
                {
                    TempData["State"] = 2;
                    return RedirectToAction("Edit");
                }
            }
            var moviesFormViewModel = new MoviesFormViewModel
            {
                Movie = movie,
                Genres = db.Genres
            };
            return View(moviesFormViewModel);

        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var movie = db.Movies.Find(id);
            if (movie == null)
                return HttpNotFound();

            return View(movie);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            try
            {
                db.SaveChanges();
                TempData["State"] = 5;
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["State"] = 4;
                return RedirectToAction("Delete");
            }

        }
    }
}

DigiMovie/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div style="background-color:lime;">
        salam
        @RenderBody()
        bye
    </div>
</body>
</html>

DigiMovie/Views/Shared/_Blue.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="background-color:aqua">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_Green.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="background-color:lime">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - وب سایت دیجی مووی</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/css-admin")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("دیجی مووی", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a href="/"><img src="/Images/digimovie.jpg" alt="دیجی مووی" title="وب سایت دیجی مووی" style="width:60px;height:50px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Contact","Home")"><i class="fa fa-envelope"></i> &nbsp; تماس با ما</a></li>
                    <li><a href="@Url.Action("About","Home")"><i class="fa fa-info"></i> &nbsp; درباره ما</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
                            مشتریان
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Create","Customers")"><i class="fa fa-user-plus"></i>&nbsp; افزودن</a></li>
                            <li><a href="@Url.Action("Index", "Customers")"><i class="fa fa-group"></i>&nbsp; مدیریت</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-film"></i>
                            فیلم
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Create","Movies")"><i class="fa fa-user-plus"></i>&nbsp; افزودن</a></li>
                            <li><a href="@Url.Action("Index", "Movies")"><i class="fa fa-group"></i>&nbsp; مدیریت</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("Index","Home")"><i class="fa fa-home"></i> &nbsp; صفحه اصلی</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>  کلیه حقوق متعلق به وب سایت دیجی مووی می باشد - 1396 &copy; </p>
        </footer>
    </div>
    @*<script>
        alert('hi');
    </script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_LayoutDrakly.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - وب سایت دیجی مووی</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/css-admin")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("دیجی مووی", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a href="/"><img src="/Images/digimovie.jpg" alt="دیجی مووی" title="وب سایت دیجی مووی" style="width:60px;height:50px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Contact")"><i class="fa fa-user"></i> &nbsp; تماس با ما</a></li>
                    <li><a href="@Url.Action("About")"><i class="fa fa-info"></i> &nbsp; درباره ما</a></li>
                    <li><a href="@Url.Action("Index")"><i class="fa fa-home"></i> &nbsp; صفحه اصلی</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>  کلیه حقوق متعلق به وب سایت دیجی مووی می باشد - 1396 &copy; </p>
        </footer>
    </div>
    @*<script>
        alert('hi');
    </script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_LayoutSlate.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - وب سایت دیجی مووی</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/css-admin")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("دیجی مووی", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a href="/"><img src="/Images/digimovie.jpg" alt="دیجی مووی" title="وب سایت دیجی مووی" style="width:60px;height:50px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Contact")"><i class="fa fa-user"></i> &nbsp; تماس با ما</a></li>
                    <li><a href="@Url.Action("About")"><i class="fa fa-info"></i> &nbsp; درباره ما</a></li>
                    <li><a href="@Url.Action("Index")"><i class="fa fa-home"></i> &nbsp; صفحه اصلی</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>  کلیه حقوق متعلق به وب سایت دیجی مووی می باشد - 1396 &copy; </p>
        </footer>
    </div>
    @*<script>
        alert('hi');
    </script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_LayoutSolar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - وب سایت دیجی مووی</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/css-admin")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("دیجی مووی", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a href="/"><img src="/Images/digimovie.jpg" alt="دیجی مووی" title="وب سایت دیجی مووی" style="width:60px;height:50px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Contact")"><i class="fa fa-user"></i> &nbsp; تماس با ما</a></li>
                    <li><a href="@Url.Action("About")"><i class="fa fa-info"></i> &nbsp; درباره ما</a></li>
                    <li><a href="@Url.Action("Index")"><i class="fa fa-home"></i> &nbsp; صفحه اصلی</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>  کلیه حقوق متعلق به وب سایت دیجی مووی می باشد - 1396 &copy; </p>
        </footer>
    </div>
    @*<script>
        alert('hi');
    </script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_LayoutSuperhero.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - وب سایت دیجی مووی</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/css-admin")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("دیجی مووی", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a href="/"><img src="/Images/digimovie.jpg" alt="دیجی مووی" title="وب سایت دیجی مووی" style="width:60px;height:50px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Contact")"><i class="fa fa-user"></i> &nbsp; تماس با ما</a></li>
                    <li><a href="@Url.Action("About")"><i class="fa fa-info"></i> &nbsp; درباره ما</a></li>
                    <li><a href="@Url.Action("Index")"><i class="fa fa-home"></i> &nbsp; صفحه اصلی</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>  کلیه حقوق متعلق به وب سایت دیجی مووی می باشد - 1396 &copy; </p>
        </footer>
    </div>
    @*<script>
        alert('hi');
    </script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_LayoutUnited.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - وب سایت دیجی مووی</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/css-admin")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("دیجی مووی", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a href="/"><img src="/Images/digimovie.jpg" alt="دیجی مووی" title="وب سایت دیجی مووی" style="width:60px;height:50px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Contact")"><i class="fa fa-user"></i> &nbsp; تماس با ما</a></li>
                    <li><a href="@Url.Action("About")"><i class="fa fa-info"></i> &nbsp; درباره ما</a></li>
                    <li><a href="@Url.Action("Index")"><i class="fa fa-home"></i> &nbsp; صفحه اصلی</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>  کلیه حقوق متعلق به وب سایت دیجی مووی می باشد - 1396 &copy; </p>
        </footer>
    </div>
    @*<script>
        alert('hi');
    </script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_OwnerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - وب سایت دیجی مووی</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("دیجی مووی", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("تماس با ما", "Contact", "Home")</li>
                    <li>@Html.ActionLink("درباره ما", "About", "Home")</li>
                    <li>@Html.ActionLink("صفحه اصلی", "Index", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>  کلیه حقوق متعلق به وب سایت دیجی مووی می باشد - 1396 &copy; </p>
        </footer>
    </div>
    @*<script>
        alert('hi');
    </script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_Red.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="background-color:indianred">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DigiMovie/Views/Shared/_testPartial.cshtml
<p style="background-color:chocolate;font:40pt tahoma;width:7in;height:3in;border:solid;border-radius:19px">
    this is content form partial view
</p>